### ISSUE TITLE
Release a version

### ISSUE THREAD

**Issue by svenluijten** [adamwojs/php-cs-fixer-phpdoc-force-fqcn#2]
Hi! First off, thanks for this fixer, it works great 😄 

Would you mind tagging & releasing a version though? Right now, I'm using `1.0.x-dev` as a version constraint in my `composer.json`, but this is not great and prone to breaking whenever something changes in this repo. 

Thanks in advance!

**Comment by adamwojs** [comment]
Hi @svenluijten. 

> Hi! First off, thanks for this fixer, it works great 😄

I'm glad to hear that!

> Would you mind tagging & releasing a version though? 

Sure, no problem. I will do this when #3 will be solved 😉

**Comment by adamwojs** [comment]
Done: https://github.com/adamwojs/php-cs-fixer-phpdoc-force-fqcn/releases/tag/v1.0
